/* Generated By:JavaCC: Do not edit this line. WebGrammarParserConstants.java */
package de.haumacher.webgrammar.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface WebGrammarParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMMENT = 6;
  /** RegularExpression Id. */
  int GRAMMAR = 7;
  /** RegularExpression Id. */
  int STRING = 8;
  /** RegularExpression Id. */
  int INTEGER = 9;
  /** RegularExpression Id. */
  int IDENTIFIER = 10;
  /** RegularExpression Id. */
  int LETTER = 11;
  /** RegularExpression Id. */
  int DIGIT = 12;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\u00a0\"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<COMMENT>",
    "\"grammar\"",
    "<STRING>",
    "<INTEGER>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\"@\"",
    "\"(\"",
    "\",\"",
    "\")\"",
    "\".\"",
    "\"=\"",
    "\"->\"",
    "\"|\"",
    "\"~\"",
    "\"[\"",
    "\"]\"",
    "\"?\"",
    "\"*\"",
    "\"+\"",
    "\"-\"",
    "\"\\\\epsilon\"",
    "\"...\"",
  };

}
