/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package de.haumacher.webgrammar.webidl.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INTEGER = 1;
  /** RegularExpression Id. */
  int FLOAT = 2;
  /** RegularExpression Id. */
  int IDENTIFIER = 3;
  /** RegularExpression Id. */
  int STRING = 4;
  /** RegularExpression Id. */
  int WHITESPACE = 5;
  /** RegularExpression Id. */
  int OTHER = 6;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<INTEGER>",
    "<FLOAT>",
    "<IDENTIFIER>",
    "<STRING>",
    "<WHITESPACE>",
    "<OTHER>",
    "\"callback\"",
    "\"=\"",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\"interface\"",
    "\"{\"",
    "\"}\"",
    "\"partial\"",
    "\"dictionary\"",
    "\"exception\"",
    "\"enum\"",
    "\",\"",
    "\"typedef\"",
    "\"implements\"",
    "\"const\"",
    "\"null\"",
    "\"true\"",
    "\"false\"",
    "\"-\"",
    "\"Infinity\"",
    "\"NaN\"",
    "\"stringifier\"",
    "\"attribute\"",
    "\"static\"",
    "\"getter\"",
    "\"setter\"",
    "\"creator\"",
    "\"deleter\"",
    "\"legacycaller\"",
    "\"optional\"",
    "\"[\"",
    "\"]\"",
    "\".\"",
    "\"...\"",
    "\":\"",
    "\"<\"",
    "\">\"",
    "\"?\"",
    "\"Date\"",
    "\"DOMString\"",
    "\"any\"",
    "\"boolean\"",
    "\"byte\"",
    "\"double\"",
    "\"float\"",
    "\"long\"",
    "\"object\"",
    "\"octet\"",
    "\"or\"",
    "\"sequence\"",
    "\"short\"",
    "\"unsigned\"",
    "\"void\"",
    "\"inherit\"",
    "\"unrestricted\"",
    "\"readonly\"",
  };

}
